/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;
import Modelo.Livros;

/**
 *
 * @author 36127512021.2
 */
public class ExibirCadastro extends javax.swing.JFrame {

    /**
     * Creates new form ExibirCadstro
     */
    public ExibirCadastro() {
        initComponents();
    }
    public void exportarDados (Livros model){
            lblautor.setText(model.getAutor());
            lbltitulo.setText(model.getTítulo());
            lblcodigo.setText(model.getCódigo());
            lblpreço.setText(model.getPreço());
            lbledição.setText (model.getEdição());
            lblquantidade.setText(model.getQuantidade());
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();
        lblautor = new javax.swing.JLabel();
        lbltitulo = new javax.swing.JLabel();
        lblcodigo = new javax.swing.JLabel();
        lblpreço = new javax.swing.JLabel();
        lbledição = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblquantidade = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(500, 500));
        setResizable(false);
        setSize(new java.awt.Dimension(500, 500));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("EXIBIR CADASTRO DE LIVROS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 10, 380, 40);

        jLabel2.setText("AUTOR:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(50, 64, 60, 20);

        jLabel3.setText("TÍTULO:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(50, 104, 60, 20);

        jLabel4.setText("CÓDIGO IBSN:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(50, 150, 140, 14);

        jLabel5.setText("PREÇO:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(50, 194, 110, 20);

        jLabel6.setText("NÚMERO DE EDIÇÃO:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 250, 150, 20);

        Voltar.setText("VOLTAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(170, 340, 80, 30);
        getContentPane().add(lblautor);
        lblautor.setBounds(190, 60, 80, 30);
        getContentPane().add(lbltitulo);
        lbltitulo.setBounds(190, 104, 70, 30);
        getContentPane().add(lblcodigo);
        lblcodigo.setBounds(190, 150, 80, 30);
        getContentPane().add(lblpreço);
        lblpreço.setBounds(190, 190, 90, 30);
        getContentPane().add(lbledição);
        lbledição.setBounds(190, 234, 90, 30);

        jLabel7.setText("QUANTIDADE DE LIVROS");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 300, 200, 30);
        getContentPane().add(lblquantidade);
        lblquantidade.setBounds(220, 300, 90, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        dispose();
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExibirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExibirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExibirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExibirCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExibirCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Voltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblautor;
    private javax.swing.JLabel lblcodigo;
    private javax.swing.JLabel lbledição;
    private javax.swing.JLabel lblpreço;
    private javax.swing.JLabel lblquantidade;
    private javax.swing.JLabel lbltitulo;
    // End of variables declaration//GEN-END:variables
}
