/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;
import Modelo.Livros;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author 36127512021.2
 */
public class TelaCadastro extends javax.swing.JFrame {

    /**
     * Creates new form TelaCadastro
     */
    public TelaCadastro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Cadastrar = new javax.swing.JButton();
        Deletar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        autor = new javax.swing.JTextField();
        titulo = new javax.swing.JTextField();
        codigo = new javax.swing.JTextField();
        preço = new javax.swing.JTextField();
        edição = new javax.swing.JTextField();
        quantidade = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Voltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 600));
        setResizable(false);
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        Cadastrar.setText("CADASTRAR");
        Cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarActionPerformed(evt);
            }
        });
        getContentPane().add(Cadastrar);
        Cadastrar.setBounds(270, 60, 140, 40);

        Deletar.setText("DELETAR");
        Deletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeletarActionPerformed(evt);
            }
        });
        getContentPane().add(Deletar);
        Deletar.setBounds(270, 120, 140, 40);

        jLabel1.setText("CADASTRO DE LIVROS");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(131, 0, 165, 44);

        jLabel2.setText("Autor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 60, 57, 35);
        getContentPane().add(autor);
        autor.setBounds(110, 60, 140, 30);
        getContentPane().add(titulo);
        titulo.setBounds(110, 100, 140, 30);
        getContentPane().add(codigo);
        codigo.setBounds(110, 140, 140, 30);
        getContentPane().add(preço);
        preço.setBounds(110, 190, 140, 30);
        getContentPane().add(edição);
        edição.setBounds(110, 240, 140, 30);
        getContentPane().add(quantidade);
        quantidade.setBounds(110, 290, 140, 30);

        jLabel3.setText("Título");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 60, 30);

        jLabel4.setText("Código ISBN");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 140, 80, 30);

        jLabel5.setText("Preço");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 190, 50, 30);

        jLabel6.setText("Número Edição");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 230, 100, 40);

        jLabel7.setText("Quantidade");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 290, 70, 30);

        jLabel8.setText("Para deletar um livro do banco de dados, é preciso ");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(520, 44, 260, 30);

        jLabel9.setText("digitar o nome do título e apartar o botão deletar.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(520, 80, 280, 20);

        jLabel10.setText("1");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(480, 50, 40, 20);

        jLabel11.setText("IMPORTANTE");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(610, 0, 110, 50);

        Voltar.setText("VOLTAR");
        Voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarActionPerformed(evt);
            }
        });
        getContentPane().add(Voltar);
        Voltar.setBounds(280, 190, 120, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarActionPerformed
        Livros model = new Livros();
        ExibirCadastro EXI = new ExibirCadastro(); 
        
        if ( (autor.getText().equals("")) && (titulo.getText().equals("")) && (codigo.getText().equals("")) && (preço.getText().equals("")) && (edição.getText().equals("")) && (quantidade.getText().equals("")) ){
           JOptionPane.showMessageDialog(null, "NÃO PODE HAVER CAMPOS EM BRANCO!!!!\n"+
                                                "PREENCHA TODOS ELES !!!!");
            autor.setText("");
            titulo.setText("");
            codigo.setText("");
            preço.setText("");
            edição.setText("");
            quantidade.setText("");
            
            setVisible(true);
        }
        else{
            

           //fazendo referencia aos metodos set do empregr
            
           model.setAutor(autor.getText());
           model.setTítulo(titulo.getText());
           model.setCódigo(codigo.getText());
           model.setPreço(preço.getText());
           model.setEdição(edição.getText());
           model.setQuantidade(quantidade.getText());
           
            EXI.exportarDados(model);
            EXI.setVisible(true);
           
       }
        
        
        
        
        
        
        
        
        try //tratamento de exceção
        {

            String A = autor.getText();
            String T = titulo.getText();
            String C = codigo.getText();
            String P = preço.getText();
            String E = edição.getText();
            String Q = quantidade.getText();
            

            String url = "jdbc:mysql://localhost/bdlivros";
            String sql = "INSERT INTO livros(Autor,Titulo,Codigo,Preço,Edição,Quantidade) values ('"+A+"','"+T+"','"+C+"','"+P+"','"+E+"','"+Q+"' )";

            Connection conexao = DriverManager.getConnection(url, "root",""); //comando de conexão com banco

            PreparedStatement atualizar = conexao.prepareStatement(sql);

            atualizar.executeUpdate();//método

            JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");

        }

        catch(Exception erro) {

            JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);

        }

    }//GEN-LAST:event_CadastrarActionPerformed

    private void DeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeletarActionPerformed
        try{ //tratamento de exceção
            String T = titulo.getText();
            String url = "jdbc:mysql://localhost/bdlivros";
            String sql =  "DELETE FROM livros WHERE Titulo='"+T+"'";
            Connection conexao = DriverManager.getConnection(url, "root",""); //comando de conexão com banco
            PreparedStatement atualizar = conexao.prepareStatement(sql);
            atualizar.executeUpdate();//método

            JOptionPane.showMessageDialog(null,"Deletado com sucesso!");
        }
        catch(Exception erro)
        {

            JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
    }//GEN-LAST:event_DeletarActionPerformed
    }
    private void VoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarActionPerformed
        MenuOpçoes MEN = new MenuOpçoes();
        MEN.setVisible(true);
    }//GEN-LAST:event_VoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaCadastro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaCadastro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cadastrar;
    private javax.swing.JButton Deletar;
    private javax.swing.JButton Voltar;
    private javax.swing.JTextField autor;
    private javax.swing.JTextField codigo;
    private javax.swing.JTextField edição;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField preço;
    private javax.swing.JTextField quantidade;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
