/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;

/**
 *
 * @author 36127512021.2
 */
public class TelaPesquisa extends javax.swing.JFrame {

    /**
     * Creates new form TelaPesquisa
     */
    public TelaPesquisa() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        titulo = new javax.swing.JTextField();
        pesquisar = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("DIGITE O TÍTULO DO LIVRO");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 170, 40);

        titulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tituloActionPerformed(evt);
            }
        });
        getContentPane().add(titulo);
        titulo.setBounds(100, 60, 190, 40);

        pesquisar.setText("PESQUISAR");
        pesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesquisarActionPerformed(evt);
            }
        });
        getContentPane().add(pesquisar);
        pesquisar.setBounds(60, 120, 110, 50);

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(220, 120, 120, 50);

        jButton1.setText("FAZER O EMPRÉSTIMO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 210, 160, 50);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tituloActionPerformed

        String url = "jdbc:mysql://localhost/bdlivros";

        String sql = "SELECT * FROM Livros WHERE Titulo = '"+titulo.getText()+"'";
        String Autor = null;
        String Titulo = null;
        String Codigo = null;
        String Preço = null;
        String Edição = null;
        String Quantidade = null;

        try
        {

            Connection conexao = DriverManager.getConnection(url, "root","");

            PreparedStatement pesquisa = conexao.prepareStatement(sql);

            ResultSet resultado = pesquisa.executeQuery();

            while (resultado.next()) {

                Autor  = resultado.getString("Autor");
                Titulo = resultado.getString("Titulo");
                Codigo = resultado.getString("Codigo");
                Preço = resultado.getString("Preço");
                Edição = resultado.getString("Edição");
                Quantidade = resultado.getString("Quantidade");

            }

            JOptionPane.showMessageDialog(null,"Dados encontrados com sucesso!\n"+
                "------------------------------\n"+
                "AUTOR  : "+Autor+"\n"+
                "TITULO : "+Titulo+"\n"+
                "CODIGO : "+Codigo+"\n"+
                "PREÇO: "+Preço+"\n"+
                "EDIÇÃO : "+Edição+"\n"+
                "QUANTIDADE : "+Quantidade+"\n"+        
                "------------------------------");

        }

        catch(Exception erro) {

            JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);

        }

    }//GEN-LAST:event_tituloActionPerformed

    private void pesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesquisarActionPerformed

        String A = null;
        String T = null;
        String C = null;
        String P = null;
        String E = null;
        String Q = null;

        try
        {

            String url = "jdbc:mysql://localhost/bdlivros";

            Connection conexao = DriverManager.getConnection(url, "root","");

            String sql = "SELECT * FROM Livros WHERE Titulo = '"+titulo.getText()+"'";

            PreparedStatement pesquisa = conexao.prepareStatement(sql);

            ResultSet resultado = pesquisa.executeQuery();

            while (resultado.next()) {

                A  = resultado.getString("Autor");
                T = resultado.getString("Titulo");
                C = resultado.getString("Codigo");
                P = resultado.getString("Preço");
                E = resultado.getString("Edição");
                Q = resultado.getString("Quantidade");

                JOptionPane.showMessageDialog(null,"Dados encontrados com sucesso!\n"+
                    "------------------------------\n"+
                "AUTOR  : "+A+"\n"+
                "TITULO : "+T+"\n"+
                "CODIGO : "+C+"\n"+
                "PREÇO: "+P+"\n"+
                "EDIÇÃO : "+E+"\n"+
                "QUANTIDADE : "+Q+"\n"+ 
                    "------------------------------");

            }

        }

        catch(Exception erro) {

            JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);

        }        // TODO add your handling code here:
    }//GEN-LAST:event_pesquisarActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        JOptionPane.showMessageDialog(null, "SEU PROGRAMA SERÁ ENCERRADO!");
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      TelaEmprestimo EMP = new TelaEmprestimo();
      
      EMP.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPesquisa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPesquisa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton pesquisar;
    private javax.swing.JTextField titulo;
    // End of variables declaration//GEN-END:variables
}
