/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visão;
import Modelo.Clientes ;
import Modelo.Livros;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author 36127512021.2
 */
public class TelaEmprestimo extends javax.swing.JFrame {

    /**
     * Creates new form TelaEmprestimo
     */
    public TelaEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        endereço = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        titulolivro = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Sair = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        cpf = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inicio = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        fim = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 400));
        setSize(new java.awt.Dimension(400, 400));
        getContentPane().setLayout(null);

        jLabel1.setText("DADOS DO CLIENTE");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 0, 150, 50);

        jLabel2.setText("Nome");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 50, 40, 20);
        getContentPane().add(nome);
        nome.setBounds(80, 50, 130, 30);

        jLabel3.setText("Endereço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 80, 80, 40);
        getContentPane().add(endereço);
        endereço.setBounds(80, 90, 130, 30);

        jLabel4.setText("CPF");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 130, 40, 30);

        titulolivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titulolivroActionPerformed(evt);
            }
        });
        getContentPane().add(titulolivro);
        titulolivro.setBounds(80, 170, 130, 30);

        jButton1.setText("CONCLUIR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(270, 50, 110, 40);

        Sair.setText("SAIR");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });
        getContentPane().add(Sair);
        Sair.setBounds(270, 160, 110, 40);

        jLabel5.setText("Título do Livro");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 174, 80, 20);

        cpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cpfActionPerformed(evt);
            }
        });
        getContentPane().add(cpf);
        cpf.setBounds(80, 130, 130, 30);

        jLabel6.setText("Data de inicio");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 214, 90, 30);
        getContentPane().add(inicio);
        inicio.setBounds(80, 210, 130, 30);

        jLabel7.setText("Data entrega");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 254, 90, 30);
        getContentPane().add(fim);
        fim.setBounds(80, 250, 130, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        JOptionPane.showMessageDialog(null, "SEU PROGRAMA SERÁ ENCERRADO!");
        dispose();
    }//GEN-LAST:event_SairActionPerformed

    private void titulolivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titulolivroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_titulolivroActionPerformed

    private void cpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cpfActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        Clientes model = new Clientes();
        ExibirEmprestimo EXI = new ExibirEmprestimo(); 
        
        if ( (nome.getText().equals("")) && (endereço.getText().equals("")) && (cpf.getText().equals("")) && (titulolivro.getText().equals("")) ){
           JOptionPane.showMessageDialog(null, "NÃO PODE HAVER CAMPOS EM BRANCO!!!!\n"+
                                                "PREENCHA TODOS ELES !!!!");
            nome.setText("");
            endereço.setText("");
            cpf.setText("");
            titulolivro.setText("");           
            
            setVisible(true);
        }
        else{
            

           //fazendo referencia aos metodos set do empregr
            
           model.setNome(nome.getText());
           model.setEndereço(endereço.getText());
           model.setCpf(cpf.getText());
           model.setTitulo(titulolivro.getText());
           model.setInicio(inicio.getText());
           model.setFim(fim.getText());
           
            EXI.exportarDados(model);
            EXI.setVisible(true);
           
       }
        
        
        
        try //tratamento de exceção
	   {
               
               String N = nome.getText();
               String E = endereço.getText();
               String C = cpf.getText();
               String T = titulolivro.getText();
               
                String url = "jdbc:mysql://localhost/bdlivros";
                
                String sql1 =  "DELETE FROM Livros WHERE Titulo='"+T+"'";
                Connection conexao = DriverManager.getConnection(url, "root",""); //comando de conexão com banco
                PreparedStatement atualizar = conexao.prepareStatement(sql1);
                atualizar.executeUpdate();//método
                
                String url1 = "jdbc:mysql://localhost/bdlivros";  
                String sql = "INSERT INTO clientes(Nome,Endereço,CPF,Titulo) values ('"+N+"','"+E+"','"+C+"','"+T+"' )";

	     //Connection conexao = DriverManager.getConnection(url, "root",""); //comando de conexão com banco

	     //PreparedStatement atualizar = conexao.prepareStatement(sql);

	     atualizar.executeUpdate();//método

	     JOptionPane.showMessageDialog(null,"Cadastrado com sucesso!");
    
	   }
	  
	   catch(Exception erro) { 
           
              JOptionPane.showMessageDialog(null,"Erro na Conexão com Banco de Dados : "+erro);
               
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Sair;
    private javax.swing.JTextField cpf;
    private javax.swing.JTextField endereço;
    private javax.swing.JTextField fim;
    private javax.swing.JTextField inicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField nome;
    private javax.swing.JTextField titulolivro;
    // End of variables declaration//GEN-END:variables
}
